openapi: 3.0.0
info:
  description: API documentation for the Track the Thing, a simple application to enable long distance bike races to
    better manage GPS tracker stock. <br>
    It has been developed by Oli M-C and Ben Kirby to support races held by Lost Dot.
  version: 0.0.1
  title: Track the thing
  contact:
    email: hello@olimc.co.uk
  #license: #todo Research and add license
    #name: "TBA"
    #url: ""
#host: "TBA"
#basePath: "TBA"
externalDocs:
  description:
  url:
tags:
- name: riders
  description: Operations concerning riders
- name: trackers
  description: Operations concerning trackers
- name: races
  description: Operations concernng races
paths:
  /riders:
    post:
      tags:
      - riders
      summary: Add a new rider
      description:
      operationId: addRider
      requestBody:
        description: Add a new rider
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRider'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostPatchRiderResponse'
    get:
      tags:
        - riders
      summary: Get a list of riders
      operationId: getRiderList
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/RaceFilter'
      responses:
        200:
          description: List of riders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiderList'
  /riders/{rider_id}:
    get:
      tags:
        - riders
      summary: Retrive information about one rider
      parameters:
        - $ref: '#/components/parameters/RiderId'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
    patch:
      tags:
        - riders
      summary: Change basic information about a rider
      operationId: patchRider
      parameters:
        - $ref: '#/components/parameters/RiderId'
      requestBody:
        description: Change information about one rider
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchRider'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostPatchRiderResponse'
  /riders/{rider_id}/assignTracker:
    post:
      parameters:
        - $ref: '#/components/parameters/RiderId'
      tags:
        - riders
        - trackers
      summary: Assign a tracker to a rider
      operationId: addTrackerToRider
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignTracker'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiderTrackerList'
        # error tracker already assigned to someone else?
        #
  /riders/{rider_id}/removeTracker:
    post:
      parameters:
        - $ref: '#/components/parameters/RiderId'
      tags:
        - riders
        - trackers
      summary: Remove a tracker from a rider
      operationId: removeTrackerFromRider
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveTracker'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiderTrackerList'
        # error tracker not assigned to rider
  /riders/{rider_id}/assignRace:
    post:
      parameters:
        - $ref: '#/components/parameters/RiderId'
      tags:
        - riders
        - trackers
      summary: Assign a rider to a Race
      operationId: assignRiderToRace
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RaceCode'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                # todo - what should this respond with?
        # error race doesnt exist
  /riders/{rider_id}/{race_id}/{checkpoint_id}/assignArrival:
    post:
      parameters:
        - $ref: '#/components/parameters/RiderId'
        - $ref: '#/components/parameters/Race'
        - $ref: '#/components/parameters/CheckpointID'
      tags:
        - riders
        - races
      summary: Assign arrival of a rider to a checkpoint
      operationId: assignArrivalOfRider
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckpointSeen'
      responses:
        200:
          description: Rider response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActiveRace'
  /races:
    get:
      tags:
        - races
      summary: Get information on all races
      operationId: getRacesList
      responses:
        200:
          description: List of all races
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaceList'
  /races/{race_id}:
    parameters:
      - $ref: '#/components/parameters/Race'
    get:
      tags:
        - races
    description: Retrive information about a race
    operationId: getRace
    response:
      200:
        schema:
          $ref: '#/components/schemas/Race'
  /races/{race_id}/riders:
    parameters:
      - $ref: '#/components/parameters/Race'
    get:
      tags:
        - races
        - riders
    description: Retrive a list of all riders assigned to a race
    response:
      200:
        schema:
          $ref: '#/components/schemas/RiderList'
  /races/{race_id}/{checkpoint_id}:
    parameters:
      - $ref: '#/components/parameters/Race'
    get:
      tags:
        - races
      description: See a list of riders who have passed through a checkpoint
    response:
      200:
        schema:
          $ref: '#/components/schemas/RiderList'
  /trackers:
    post:
      tags:
        - trackers
      summary: Add a new tracker
      operationId: addNewTracker
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTracker'
      responses:
        200:
          description: Tracker added to db successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostTrackerResponse'
    get:
      tags:
        - trackers
  /trackers/{tracker_id}:
    get:
      tags:
        - trackers
    patch:
      tags:
        - trackers
components:
  parameters:
    Limit:
      name: limit
      in: query
      description: Limit the number of responses to return
      required: false
      default: 25
      schema:
        $ref: '#/components/schemas/LimitParam'
    RaceFilter:
      name: race
      in: query
      description: Limit the return of riders to one or more races
      schema:
        $ref: '#/components/schemas/RaceParam'
    Race:
      name: race_id
      in: path
      description: Race Code
      required: true
      schema:
        $ref: '#/components/schemas/RaceCode'
    CheckpointID:
      name: checkpoint_id
      in: path
      description: Checkpoint ID
      required: true
      schema:
        $ref: '#/components/schemas/Checkpoint'
    RiderId:
      name: rider_id
      in: path
      description: Rider ID
      required: true
      schema:
        $ref: '#/components/schemas/RiderId'
  schemas:
    RemoveTracker:
      type: object
      properties:
        trackerId:
          $ref: '#/components/schemas/Id'
        depositToBeReturned:
          $ref: '#/components/schemas/DepositAmount'
    AssignTracker:
      type: object
      properties:
        trackerId:
          $ref: '#/components/schemas/Id'
        depositPaid:
          $ref: '#/components/schemas/DepositAmount'
    PostTracker:
      type: object
      properties:
        esnNumber:
          $ref: '#/components/schemas/ESNNumber'
          required: true
        workingStatus:
          $ref: '#/components/schemas/WorkingStatus'
        loanStatus:
          $ref: '#/components/schemas/LoanStatus'
        lastTestDate:
          $ref: '#/components/schemas/timestamp'
        purchaseDate:
          $ref: '#/components/schemas/timestamp'
        warrantyExpiry:
          $ref: '#/components/schemas/timestamp'
        owner:
          $ref: '#/components/schemas/Owner'
    PostTrackerResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        esnNumber:
          $ref: '#/components/schemas/ESNNumber'
    Owner:
      type: string
      enum:
        - lostDot
        - riderOwned
        - thirdParty
    LimitParam:
      type: integer
      example: 5
    RaceParam:
      type: string
      example: TCR06
    PatchRider:
      type:
        object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          $ref: '#/components/schemas/LastName'
        email:
          $ref: '#/components/schemas/Email'
    PostRider:
      type:
        object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
          required: true
        lastName:
          $ref: '#/components/schemas/LastName'
          required: true
        email:
          $ref: '#/components/schemas/Email'
          required: true
    PostPatchRiderResponse:
      type:
        object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          $ref: '#/components/schemas/LastName'
        email:
          $ref: '#/components/schemas/Email'
        id:
          $ref: '#/components/schemas/Id'
    RiderList:
      type: array
      items:
        $ref: '#/components/schemas/Rider'
    Rider:
      type:
        object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          $ref: '#/components/schemas/lastName'
        email:
          $ref: '#/components/schemas/Email'
        id:
          $ref: '#/components/schemas/Id'
        trackers:
          $ref: '#/components/schemas/RiderTrackerList'
        totalDeposit:
          $ref: '#/components/schemas/DepositAmount'
        activeRace:
          $ref: '#/components/schemas/ActiveRace'
    ActiveRace:
      type: object
      properties:
        raceCode:
          $ref: '#/components/schemas/RaceCode'
        checkPoints:
          $ref: '#/components/schemas/CheckpointList'
    CheckpointList:
      type: array
      items:
        $ref: '#/components/schemas/CheckpointSeen'
    CheckpointSeen:
      type: object
      properties:
        checkPoint:
          $ref: '#/components/schemas/Checkpoint'
        timeSeen:
          $ref: '#/components/schemas/dateTime'
    Checkpoint:
      type: string
      example: CP2
    dateTime:
      type: object
      properties:
        timestamp:
          $ref: '#/components/schemas/timestamp'
        timeReadable:
          $ref: '#/components/schemas/timeReadable'
    RiderTrackerList:
      type: array
      items:
        $ref: '#/components/schemas/RiderTracker'
    RiderTracker:
      type: object
      properties:
        esnNumber:
          $ref: '#/components/schemas/ESNNumber'
        id:
          $ref: '#/components/schemas/Id'
        depositAmount:
          $ref: '#/components/schemas/DepositAmount'
        workingStatus:
          $ref: '#/components/schemas/WorkingStatus'
    Id:
      type: integer
      example: 142
    ESNNumber:
      type: string
      example: 123456789
    DepositAmount:
      type: float
      example: 200.4
    LoanStatus:
      type: string
      enum:
        - with_rider
        - not_loaned
        - other
    WorkingStatus:
      type: string
      enum:
        - working
        - broken
        - unknown
    RaceList:
      type: array
      items:
        $ref: '#/components/schemas/Race'
    Race:
      type: object
      properties:
        dateStart:
          $ref: '#/components/schemas/dateTime'
        dateEnd:
          $ref: '#/components/schemas/dateTime'
        name:
          $ref: '#/components/schemas/RaceName'
        code:
          $ref: '#/components/schemas/RaceCode'
    RaceCode:
      type: string
      description: Code for Race
      example: TCR06
    timestamp:
      type: integer
      description: Unix Epoch timestamp
    timeReadable:
      type: string
      description: ISO Format Date Time string
      example: '2018-01-03T23:00:15'
    RaceName:
      type: string
      description: Name of Race
      example: Transcontinental no. 6
    FirstName:
      type: string
      description: First name of rider
      example: Graham
    LastName:
      type: string
      description: Last name of rider
      example: Dodds
    Email:
      type: string
      example: hello@email.com

